### ISSUE TITLE
duplicate service-registration in META-INF/services, failing the native-image build

### ISSUE THREAD

**Issue by BartRobeyns** [micronaut-projects/micronaut-profiles#102]
When building a graalvm version of the service (using build-native-image.sh), I sometimes run into 
Message: Multiple possible bean candidates found: [io.micronaut.jackson.ObjectMapperFactory, io.micronaut.jackson.ObjectMapperFactory]

This is caused by duplicate entries in META-INF/services/com.fasterxml.jackson.core.ObjectCodec: it contains com.fasterxml.jackson.databind.ObjectMapper twice.

This is because the ServicesResourceTransformer of the maven-shade plugin doesn't clean out an already existing service-registration (sounds like a bug in the transformer to me).

It can be worked around by running 
./mvnw clean package
iso
./mvnw package
at the start of build-native-image.sh

**Comment by BartRobeyns** [comment]
If you want, I'll create a pull request to include the workaround in the script - but it's such a small thing a PR seems a bit over the top :)

**Comment by graemerocher** [comment]
This is already been fixed and we no longer include `build-native-image.sh`. Thanks
