### ISSUE TITLE
Using features=spock still pulls Junit dependecies, test don't run

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-profiles#109]
## How to reproduce

create a Java app with Spock as test framework

`mn create-app foo --features=spock`

Create a Spock tests `src/test/groovy/foo/FooSpec.groovy`:

```
package foo

import spock.lang.Specification

class FooSpec extends Specification {

    def "fails fails"() {
        expect:
        false
    }
}
```

Run tests: `./gradlew test`

Test apparently do not run.

### Workaround
Remove Junit dependencies: 

```
dependencies {
	...
	testCompile "org.junit.jupiter:junit-jupiter-api"
    testCompile "io.micronaut.test:micronaut-test-junit5"
    testRuntime "org.junit.jupiter:junit-jupiter-engine"
}
// use JUnit 5 platform
test {
    useJUnitPlatform()
}
```

`./gradlew test` run tests.

## Versions

`micronautVersion: 1.1.0.M1`

**Comment by ZacharyKlein** [comment]
Fixed by the same fix for #158
