### ISSUE TITLE
Problem With Gradle Build And Spock Feature

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-profiles#158]
Using Micronaut 1.1.1 an app created with `--features spock` contains JUnit config in `build.gradle` which prevents Spock tests from running.

    mn create-app --features spock spockapp

`build.gradle` will contain the following:

    // use JUnit 5 platform
    test {
        useJUnitPlatform()
    }

Attempts to run Spock tests from Gradle result in no tests being recognized.  Removing the above config allows the tests to be run.

**Comment by graemerocher** [comment]
I think `junit-vintage-engine` is needed. See https://blog.jdriven.com/2018/10/combining-spock-junit-5-tests/
