### ISSUE TITLE
Include asciidoctor as feature

### ISSUE THREAD

**Issue by jagedn** [micronaut-projects/micronaut-profiles#164]
It could be great to have an asciidoctor feature who include repos, plugins and a basic index.adoc to promote good practiques

something as 

       mn create-app example1 --features asciidoctor,http-client,kafka 

will add to build.gradle the asciidoctor plugin and create an index (perhaps with some structured content)

**Comment by graemerocher** [comment]
Sounds reasonable. PRs welcome!
