### ISSUE TITLE
Support Micronaut Data in the CLI

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-profiles#184]
Add support for code generation from interface to a real class.
Similar how it is in JOOQ https://www.jooq.org/doc/3.11/manual/code-generation/codegen-daos/

The goal is to have code generation for: we have `ProductsRepository` and filtering depends on what user will choose, so in frontend app we have a table with products, and user can sort them by title, price, category, can sort them ascending or descending.

**Comment by benrhine** [comment]
This issue has been fixed by pr https://github.com/micronaut-projects/micronaut-profiles/pull/196. Once released you will be able to run the `mn create-repository Book [jpa|jdbc]` in order to generate a repository.
