### ISSUE TITLE
Controller tests should be generated in Kotlin when language is set to kotlin

### ISSUE THREAD

**Issue by orevial** [micronaut-projects/micronaut-profiles#193]
Creating a simple application using Kotlin with JUnit feature and then creating using mn command line to create a controller generates a Kotlin controller but a Java controller test instead of a Kotlin one. 

Example:

```shell
mn create-app com.example.my-app --lang=kotlin --features=junit
cd my-app
mn create-controller Hello
```

Produces the following rendered files:

```shell
| Rendered template Controller.kt to destination src/main/kotlin/com/example/HelloController.kt
| Rendered template ControllerTest.java to destination src/test/java/com/example/HelloControllerTest.java
```

instead of the expected rendered templates:

```shell
| Rendered template Controller.kt to destination src/main/kotlin/com/example/HelloController.kt
| Rendered template ControllerTest.kt to destination src/test/kotlin/com/example/HelloControllerTest.kt
```

Is this the intended behavior ? From what I understood profiles have been configured to generate tests with the following combination:

* Kotlin test if --lang=kotlin but no test feature defined (or spek feature is defined)
* Groovy test if --lang=kotlin and test feature spock is defined
* Java test if --lang=kotlin and test feature junit is defined

Although I can see why this is the case, I think that Kotlin developers might want to use Junit with Kotlin... what do you think ?

Tested with Micronaut 1.2.3

**Comment by orevial** [comment]
@graemerocher @ilopmar will you be interested in a PR to make tests generation more configurable based on used language and optional test feature ?

**Comment by graemerocher** [comment]
PRs are absolutely welcome!

**Comment by benrhine** [comment]
@orevial 's pr has been integrated into this pr https://github.com/micronaut-projects/micronaut-profiles/pull/198
