### ISSUE TITLE
With GraalVM 19.3  shipping JDK libraries such as libsunec.so no longer needed

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-profiles#210]
See: https://medium.com/graalvm/graalvm-19-3-0-dfdb6f4ec8ed

> In GraalVM 19.3 Native Image switched to statically linking the JDK’s native code instead of manually provided substitutions for that native code. This change is a major factor in enabling JDK 11 based GraalVM distributions on Windows. It also has no impact on startup time or memory footprint of native images and **eliminates the need for shipping JDK libraries such as libsunec.so along with native images** that use Java crypto services.

**Comment by ilopmar** [comment]
Done in #206
