### ISSUE TITLE
GraalVM Maven coordinates for substratevm

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-profiles#211]
See: https://medium.com/graalvm/graalvm-19-3-0-dfdb6f4ec8ed

> Another very important change in 19.3 is the difference in the Maven coordinates for the GraalVM Native Image related jars. The group id for the artifacts is changed from com.oracle.substratevm to org.graalvm.nativeimage.

**Comment by ilopmar** [comment]
Done in https://github.com/micronaut-projects/micronaut-profiles/pull/206

**Comment by sdelamo** [comment]
@ilopmar we need to add the dependency to the bom.

**Comment by ilopmar** [comment]
@sdelamo already done in https://github.com/micronaut-projects/micronaut-core/pull/2418. Waiting for @jameskleeh to merge those 2 PRs :smiley:

**Comment by ilopmar** [comment]
Done
