### ISSUE TITLE
OpenFaas Support in Functions

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-profiles#36]
To support deploying functions to OpenFaas you need a `Dockerfile` like the following:

```
FROM openjdk:8-jre-alpine

RUN addgroup -S app && adduser -S -g app app

WORKDIR /app
COPY build/libs/*-all.jar /app/Handler.jar

ADD https://github.com/openfaas/faas/releases/download/0.6.5/fwatchdog /usr/bin
RUN chmod +x /usr/bin/fwatchdog

USER app

ENV fprocess="java -noverify -XX:TieredStopAtLevel=1 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -jar Handler.jar"

HEALTHCHECK --interval=1s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
```

We should add a `openfaas` feature to the function profiles to generate this file.

**Comment by ilopmar** [comment]
They replied in twitter: https://twitter.com/openfaas/status/1006915116476928002

> We're not familiar with Micronaut, but would suggest raising an issue on the OpenFaaS GitHub repository so we can give you some tips on support. The watchdog proposed in the Dockerfile is very out of date.

**Comment by ZacharyKlein** [comment]
@graemerocher any quick steps to test this change?
