### ISSUE TITLE
Creating an app with Kotlin and spock should not include spek dependencies

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-profiles#46]
If you execute: 

`mn create-app example.micronaut.complete --features=kotlin,spock`

the spek dependencies are included. Thy should not. 

Moreover, `micronaut-cli.yml` should be:

```
profile: service
defaultPackage: example.micronaut
---
testFramework: spock
sourceLanguage: kotlin
```

**Comment by ZacharyKlein** [comment]
This is half resolved - the `micronaut-cli.yml` file does contain Spock as the `testFramework`. Currently each lang feature (Java/Groovy/Kotlin) has to have a "required" test feature, and there's no way to cleanly separate the two. This will have to await the CLI refactor that @jameskleeh and I have been discussing.

**Comment by benrhine** [comment]
Closing, this is no longer the case. Kotlin apps generated with the spock feature do not include `spek` dependencies and the `micronaut-cli.yml` generates as above.
