### ISSUE TITLE
Support for Graal Native image in CLI

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-profiles#67]
We should create a `graal-native-image` profile that sets up the basics needed to build a Graal native image.

An example project can be found at https://github.com/graemerocher/micronaut-graal-experiments/tree/master/hello-world-java

The changes required are:

1. A `runtimeOnly` reference to the `graal` dependency https://github.com/graemerocher/micronaut-graal-experiments/blob/master/hello-world-java/build.gradle#L45
2. A `compileOnly` reference to the SVM dependency https://github.com/graemerocher/micronaut-graal-experiments/blob/master/hello-world-java/build.gradle#L46
3. A `NettySubstitutions` java file in `src/main/java` (location can be the same as the application package) https://github.com/graemerocher/micronaut-graal-experiments/blob/master/hello-world-java/src/main/java/netty/svm/substitutions/NettySubstitutions.java
4. A `build-native-image.sh` script https://github.com/graemerocher/micronaut-graal-experiments/blob/master/hello-world-java/build-native-image.sh

Note that Graal only works on Mac OS and Linux so one wrinkle is no Windows support.

**Comment by ZacharyKlein** [comment]
@graemerocher fixed in https://github.com/micronaut-projects/micronaut-core/commit/e5231ca3f4084f5b4fb79efe6a2ccf34868367db

**Comment by graemerocher** [comment]
Thanks
