### ISSUE TITLE
Enable annotation processors in IntelliJ by default

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-profiles#75]
It is pretty common to forget ot enable annotation processors for 
To enable annotation processors by default in IntelliJ IDEA it is enough to create file `.idea/compiler.xml` with following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
    <component name="CompilerConfiguration">
        <annotationProcessing>
            <profile default="true" name="Default" enabled="true" />
        </annotationProcessing>
    </component>
</project>
```

the problem is the if you create the file before importing the project then you will be asked to rewrite the content of `.idea`. The ideal solution would be to hook into IDEA's Gradle import process and create the file right after the import but I wasn't able to figure out how to do it.

**Comment by ilopmar** [comment]
I always forgot about this so, as a workaround I enabled it by default for all projects.
You can do it in `File -> Other settings -> Default Settings -> Build, Execution, Deployment -> Compiler -> Annotation Processors`

**Comment by jameskleeh** [comment]
I don't think we can assume users are using IDEA, and also we don't have the ability to hook into the Gradle import process
