### ISSUE TITLE
Dockerfile for GraalVM

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-profiles#76]
It would be great if application with GraalVM feature would contain `Dockerfile` for the application compiled with native image

**Comment by graemerocher** [comment]
Worthy of PR? 😉

**Comment by musketyr** [comment]
@graemerocher see #81 and #80 

Sorry for 2 PR, WiFi here is very slow so I've done it using GitHub file editor.

**Comment by graemerocher** [comment]
will take a look.. thx

**Comment by musketyr** [comment]
fixed in e6d281cfbb821b91e14afe70b64772a7d66ffff2
