### ISSUE TITLE
add CompileStatic by default

### ISSUE THREAD

**Issue by jagedn** [micronaut-projects/micronaut-profiles#82]
It would be nice if the groovy profile can generate a `groovyOptionsConfig.groovy` and include it in the `build.gradle`

`groovyOptionsConfig.groovy` :
```
   withConfig(configuration) {
      ast(groovy.transform.CompileStatic)
   }
```
`build.gradle`:
```
compileGroovy {
    groovyOptions.configurationScript = file("groovyOptionsConfig.groovy")
}
```

**Comment by musketyr** [comment]
does IntelliJ Idea understand these settings by default?

**Comment by jameskleeh** [comment]
I don't necessarily think this is a good idea to do by default. It can cause surprising behavior for users who aren't aware, and it seems that it is easy enough to add after the fact.
