### ISSUE TITLE
Upgrade GraalVM Version

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-profiles#83]
The new version of GraalVM has been released:

https://www.graalvm.org/docs/release-notes/#10-rc8

one of the biggest advantages is that GraalVM artefacts are now hosted in Maven Central there is no need for maven local import any more. With the working `Dockerfile` no-one needs to install the GraalVM locally.

**Comment by ilopmar** [comment]
We currently support the latest GraalVM version, RC14.
